Implement Apache Airflow Task to Trigger Dag Runs
kestra-io/plugin-airflow pull request #3
Opened 2024-07-28 03:51 UTC by iNikitaGricenko

### What changes are being made and why?

- Implemented Task that triggers dag run in Apache Airflow (#2)
---

### How the changes have been QAed?

```yaml
  - id: trigger_dag
    type: io.kestra.plugin.airflow.TriggerDagRun
    baseUrl: http://localhost:8080
    dagId: example_dag
    checkFrequency: PT30S
      interval: PT30S
      maxIterations: 100
      maxDuration: PT1H
    options:
      basicAuthUser: airflow
      basicAuthPassword: airflow
```

---

### Setup Instructions

- Apache Airflow docker container or local application. [Official documentation for installation in docker](https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html)

2024-07-29 08:18 UTC, loicmathieu requested changes

2024-07-29 08:18 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/airflow/dags/TriggerDagRun.java
> +        title = "Whether task should wait DAG run to complete",
```suggestion
        title = "Whether task should wait fr the DAG to run to completion",
```

2024-07-29 08:18 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/airflow/dags/TriggerDagRun.java
> +        title = "Overrides the default conf payload"
```suggestion
        title = "Overrides the default configuration payload"
```

2024-07-29 08:18 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/airflow/dags/TriggerDagRun.java
> +    private WaitFor.CheckFrequency checkFrequency = WaitFor.CheckFrequency.builder().build();
I don't think it's a good idea to use another task internal property class from the core plugin in another plugin.
I think here using only a timeout and ping the DAG endpoint each second would be enough it's what we did in a lot of other tasks.

2024-07-29 08:18 UTC, loicmathieu commented on src/test/java/io/kestra/plugin/airflow/dags/TriggerDagRunTest.java
Is it possible to run Airflow easily with a simple docker compose so the test can be run inside our CI/CD

2024-07-31 16:13 UTC, iNikitaGricenko commented on src/test/java/io/kestra/plugin/airflow/dags/TriggerDagRunTest.java
I have tested using docker-compose. But it's requires a lot of services. I have asked Anna if should i use docker-compose or just disable unit tests, so we decided to just disable them

2024-07-31 16:21 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/airflow/dags/TriggerDagRun.java
> +    private WaitFor.CheckFrequency checkFrequency = WaitFor.CheckFrequency.builder().build();
I didn't see the description from Anna.

You can keep the options but I'd rather not use CheckFrequency and include a basic polling as we do in other plugins with only a maxDuration and a pollFrequency, you can take as example: https://github.com/kestra-io/plugin-airbyte/blob/master/src/main/java/io/kestra/plugin/airbyte/connections/CheckStatus.java

2024-08-01 07:23 UTC, merged